"""
Route-level tests for task retrieval, update, and deletion endpoints.
"""
from __future__ import annotations

from datetime import date, timedelta
from typing import Any, Dict, Iterator, List

import pytest
import requests


@pytest.fixture
def future_due_date() -> str:
    """Provide a due_date value that always stays in the future."""
    return (date.today() + timedelta(days=14)).isoformat()


@pytest.fixture
def task_payload_factory(future_due_date: str):
    """Return a callable that builds valid task payloads with optional overrides."""

    def _build(**overrides: Any) -> Dict[str, Any]:
        payload: Dict[str, Any] = {
            "title": "Route test task",
            "description": "Generated by task_payload_factory",
            "due_date": future_due_date,
            "priority": "medium",
            "status": "active",
        }
        payload.update(overrides)
        return payload

    return _build


@pytest.fixture
def created_tasks(
    api_base_url: str,
    auth_headers: Dict[str, str],
    task_payload_factory,
) -> Iterator[List[Dict[str, Any]]]:
    """Create a small set of tasks for list/filter tests and clean them up afterward."""
    payloads = [
        task_payload_factory(title="Filter active high", status="active", priority="high"),
        task_payload_factory(title="Filter completed low", status="completed", priority="low"),
    ]
    tasks: List[Dict[str, Any]] = []
    for payload in payloads:
        response = requests.post(
            f"{api_base_url}/tasks",
            json=payload,
            headers=auth_headers,
            timeout=10,
        )
        assert response.status_code == 201, f"Expected 201 while creating setup task, got {response.status_code}"
        tasks.append(response.json())

    yield tasks

    for task in tasks:
        requests.delete(
            f"{api_base_url}/tasks/{task['id']}",
            headers=auth_headers,
            timeout=10,
        )


def test_get_task_by_id_existing_task_returns_200_with_task_body(created_task: Dict[str, Any], api_base_url: str) -> None:
    """GET /tasks/{id} should return the created task payload for an existing task id."""
    response = requests.get(f"{api_base_url}/tasks/{created_task['id']}", timeout=10)

    assert response.status_code == 200, f"Expected 200 for existing task id, got {response.status_code}"
    body = response.json()
    assert body["id"] == created_task["id"], f"Expected id {created_task['id']}, got {body['id']}"
    assert body["title"] == created_task["title"], f"Expected matching title, got {body['title']}"


def test_get_tasks_with_status_and_priority_filters_returns_matching_tasks(
    created_tasks: List[Dict[str, Any]],
    api_base_url: str,
) -> None:
    """GET /tasks should honor status and priority filters and only return matching rows."""
    params = {"status": "active", "priority": "high"}
    response = requests.get(f"{api_base_url}/tasks", params=params, timeout=10)

    assert response.status_code == 200, f"Expected 200 for filtered list, got {response.status_code}"
    body = response.json()
    assert isinstance(body, list), f"Expected list response body, got {type(body)}"
    assert len(body) >= 1, "Expected at least one filtered task in response body"
    assert any(task["id"] == created_tasks[0]["id"] for task in body), "Expected seeded active/high task in filtered results"
    assert all(task["status"] == "active" for task in body), "Expected every filtered task to have status=active"
    assert all(task["priority"] == "high" for task in body), "Expected every filtered task to have priority=high"


def test_put_task_with_valid_status_and_priority_returns_200_with_updated_task(
    created_task: Dict[str, Any],
    api_base_url: str,
    auth_headers: Dict[str, str],
) -> None:
    """PUT /tasks/{id} should update permitted fields and return the updated task."""
    update_payload = {"status": "completed", "priority": "low"}
    response = requests.put(
        f"{api_base_url}/tasks/{created_task['id']}",
        json=update_payload,
        headers=auth_headers,
        timeout=10,
    )

    assert response.status_code == 200, f"Expected 200 for valid update payload, got {response.status_code}"
    body = response.json()
    assert body["id"] == created_task["id"], f"Expected updated task id {created_task['id']}, got {body['id']}"
    assert body["status"] == "completed", f"Expected status=completed after update, got {body['status']}"
    assert body["priority"] == "low", f"Expected priority=low after update, got {body['priority']}"


@pytest.mark.parametrize(
    ("update_payload", "expected_error_substring"),
    [
        ({"status": "done"}, "Status must be one of"),
        ({"due_date": "invalid-date"}, "Due date must be a valid date"),
        ({"description": "x" * 2001}, "Description must not exceed 2000 characters"),
    ],
)
def test_put_task_with_invalid_payload_returns_400_with_validation_error(
    created_task: Dict[str, Any],
    api_base_url: str,
    auth_headers: Dict[str, str],
    update_payload: Dict[str, Any],
    expected_error_substring: str,
) -> None:
    """PUT /tasks/{id} should reject invalid partial updates with 400 and a useful validation message."""
    response = requests.put(
        f"{api_base_url}/tasks/{created_task['id']}",
        json=update_payload,
        headers=auth_headers,
        timeout=10,
    )

    assert response.status_code == 400, f"Expected 400 for invalid update payload, got {response.status_code}"
    body = response.json()
    assert expected_error_substring in body["error"], f"Expected validation error containing '{expected_error_substring}'"


def test_delete_task_existing_task_returns_204_and_task_is_not_found_afterwards(
    api_base_url: str,
    auth_headers: Dict[str, str],
    task_payload_factory,
) -> None:
    """DELETE /tasks/{id} should return 204 and make subsequent GET return 404 for the deleted task."""
    create_response = requests.post(
        f"{api_base_url}/tasks",
        json=task_payload_factory(title="Delete-me task"),
        headers=auth_headers,
        timeout=10,
    )
    assert create_response.status_code == 201, f"Expected 201 while creating deletable task, got {create_response.status_code}"
    created_task = create_response.json()

    delete_response = requests.delete(f"{api_base_url}/tasks/{created_task['id']}", headers=auth_headers, timeout=10)
    assert delete_response.status_code == 204, f"Expected 204 on delete, got {delete_response.status_code}"
    assert delete_response.text == "", f"Expected empty response body for 204 delete, got: {delete_response.text}"

    get_response = requests.get(f"{api_base_url}/tasks/{created_task['id']}", timeout=10)
    assert get_response.status_code == 404, f"Expected 404 after deleting task, got {get_response.status_code}"
    body = get_response.json()
    assert body["error"] == "Task not found", f"Expected 'Task not found' body after delete, got: {body}"
